GET http://localhost:3000/user/1



###

POST  http://localhost:3000/user/signup
Content-Type: application/json

{
    "email":"sam",
    "password":"password"

}



###

POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"sam",
    "password":"password"

}

