GET http://localhost:3000/user/1



###

POST  http://localhost:3000/user/signup
Content-Type: application/json

{
    "email":"sam",
    "password":"password"

}



###

POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"sam",
    "password":"password"

}

###

POST  http://localhost:3000/cars/newcar
Content-Type: application/json

{
        "contact":"user url",
        "make":"make ",
        "model": "model", 
        "year": 1920,
        "AOM":"MANUAL",
        "mileage": 20,
        "price": 2025,
        "description":"you know its a car" 

}

